name: 'JSSM Automatic Visualization'
description: 'Automatically render your FSL machines to PNG or SVG flowcharts using jssm-viz'
author: 'John Haugeland <stonecypher@gmail.com>'
inputs:
  targetGlob:
    description: 'Glob to use as target.  Defaults to either `./**/*.fsl`. Usually just a filename when specified'
    default: './**/*.fsl'
  usePng:
    description: 'Include PNG format when outputting images'
    default: false
  useSvg:
    description: 'Include SVG format when outputting images'
    default: true
  useJpeg:
    description: 'Include JPEG format when outputting images (same as JPG but four letter extension)'
    default: false
  useJpg:
    description: 'Include JPG format when outputting images (same as JPEG but three letter extension)'
    default: false
  useWebP:
    description: 'Include WebP format when outputting images'
    default: false
  useDot:
    description: 'Include GraphViz DOT format when outputting (source, not an image)'
    default: false
  useJsonTree:
    description: 'Include Tree-As-JSON format when outputting (source, not an image)'
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
